on: push

jobs:
  test:
    runs-on: sre-eqx-kata
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          since-commit: ${{ github.event.before }}
          branch: ${{ github.ref_name }}
